services:
  app:
    image: nextcloud
    restart: always
    ports:
      - "8080:80"
    volumes:
      - type: volume
        source: nextcloud
        target: /var/www/html
    networks:
      - global_net
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=${MYSQL_HOST}
      - REDIS_HOST=${REDIS_HOST}
    entrypoint: >
      bash -c "
        mysql -h ${MYSQL_HOST} -u root -p ${MYSQL_ROOT_PASSWORD} << EOSQL
          CREATE DATABASE IF NOT EXISTS \`${MYSQL_DATABASE}\`;
          CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
          GRANT ALL PRIVILEGES ON \`${MYSQL_DATABASE}\`.* TO '${MYSQL_USER}'@'%';
        EOSQL
      "

networks:
  global_net:
    external: true

volumes:
  nextcloud:
