services:
  app:
    image: nextcloud
    restart: always
    ports:
      - "8080:80"
    volumes:
      - type: volume
        source: nextcloud
        target: /var/www/html
    networks:
      - global_net
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=db
      - REDIS_HOST=redis

networks:
  global_net:
    external: true

volumes:
  nextcloud:
