version: '3.8'

services:
  app:
    image: nextcloud
    restart: always
    ports:
      - "8080:80"
    volumes:
      - type: volume
        source: nextcloud
        target: /var/www/html
    environment:
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    networks:
      - global_net

networks:
  global_net:
    external: true

volumes:
  nextcloud:
