services:
  app:
    image: nextcloud
    restart: always
    ports:
      - "8080:80"
    volumes:
      - type: volume
        source: nextcloud
        target: /var/www/html
    networks:
      - global_net
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    entrypoint: >
      bash -c "
        mysql -h $DB_HOST -u root -p$MYSQL_ROOT_PASSWORD <<-EOSQL
          CREATE DATABASE IF NOT EXISTS \`$DB_NAME\`;
          CREATE USER IF NOT EXISTS '$DB_USER'@'%' IDENTIFIED BY '$DB_PASS';
          GRANT ALL PRIVILEGES ON \`$DB_NAME\`.* TO '$DB_USER'@'%';
        EOSQL
      "


networks:
  global_net:
    external: true

volumes:
  nextcloud:
